### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by arturaugusto** [lazear/dbscan#1]
Hi,
Just want to let you know that I've compiled your library to WebAssembly, and it works fast and great!
https://github.com/arturaugusto/dbscan-rust-wasm
Thank you.

**Comment by lazear** [comment]
Glad it was helpful! I've been meaning to play around with wasm myself - just curious, what are you using it for? @arturaugusto

**Comment by arturaugusto** [comment]
I'm building a web application to do realtime OCR through the camera. The user will be able do the training step by choosing a specific font from the web interface. DBSCAN play the important role of text segmentation. It will be open source! I tell you when release de first version.
